name: Release Version
on:
  workflow_run:
    workflows: ["Renderscript"]
    branches: [master]
    types:
      - completed

env:
  COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    if: (github.event.workflow_run.conclusion == 'success')

    steps:
      - uses: actions/checkout@v2
        with:
          # Make sure the release step uses its own credentials.
          persist-credentials: false

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.GH_USER_NAME }}
          GIT_AUTHOR_EMAIL:	${{ secrets.GH_USER_EMAIL }}
          GIT_COMMITTER_NAME:	${{ secrets.GH_USER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GH_USER_EMAIL }}
        run: |
          yarn install
          yarn semantic-release
